@Restaurants.API_HostAddress = https://localhost:7270
@host = https://localhost
@port = 7270
@token = CfDJ8JNLE7-DAkZCjCihCkpeOkXE7QfAh0ROjuIpb2AYc4Lp6Wp63Wqi0RfQS8hfLx4enIKCy8ddRRTiwRkHDbyl8XqVeEus0BmnlpzGOyZdLqSNjvaXGv5d1bBMyXoEuGCZV26Jgz7gIJXB8bow3auoqFeRD8JbOQ4NR7mvxiTdEHB8KlRGdm4XdrW2bC5EJOhx2TgpyZn87fnrGodFsykULNodbZIs_6bVsIBDosYasKn05w3vt8v7Zn48oBwEwLDJ7Q-zqZdWVxOjrt4SDWH7XjYv4QZlB6MqyDGSohomIoUmrazhjs8eRnQ4oVT8oYL-8J_vPgq6GxvG4TSQVoGYdmay870HtIk3upl-L0MWrGvySa--muGpZ4CtiDBzUJ8tqU516aQxbfuOnsHr8iGrmeDIOFSbhau9UBTg7qmfj8B0BBelk3D45FYO3IJb8MH1K93BqhKPIj0FH8RKToQGSyiFdeykuEW3DMneMBhenF1AWBRlLoFU4hDLRJvk5rS8Tzq5XknMP7CZi9bqVIrPTEXagaWKXWU9grbSMkDdJTzdCfGjXuATyJKX19rT_EQGCdBVAk7nj5ec_dYRPCc9PyJiedFP8M12iIfKTudwuH0bFVOuCCEs65Yswtnc-aWC20BBfgWQV2PoyjlvwTrcxII-wBJGrjMe6LImpkA5VoJycDKVFdO25j3CYEiNyxn3CKGFIDRPnzsy82JR9VubYFpU08qbrMYE9HYjvx3EyV3mgFFQy1o3XaWLerwmwf7xC7jIWEj4CF8a4WRBvV9eM3UaWcldU9TRHnjHmMlBPLA2Zpm6r5MrfEjq9jPzhvd7NeeBLdIncxGiwd8149oWO7AqcHKSkvYV25CB7W8mRmjOIxOMH8B-6_2oNL-WlUHsWg

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=10&pageNumber=2&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3


###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1009
Authorization: Bearer {{token}}


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

GET https://localhost:7005/api/restaurants/1009
Authorization: Bearer {{token}}


###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1009
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Updated name",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET https://localhost:7005/api/restaurants/3/dishes/7



###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###