@Restaurants.API_HostAddress = https://localhost:7270
@host = https://localhost
@port = 7270
@token = CfDJ8JNLE7-DAkZCjCihCkpeOkVUMD4jY7cDoDZpidY0DbvcrN2d2nj0Pbqybymk8SoZ6nDKh5WcEb23CuDsrPkTiFssw5IKcjQeuiROZW7IkCiLH47IhbSePm4McVElTGrIZrK-UikrjaO7f5urkYudBjAp3sZ8oDC9CVVKmsZ6hq9vqfmDT6l1BI0auKOQO8wr12T9DC5PazV-fNFnNhoDWw4rRuvZRFDgGAW4P3MLA2rcNHjjkvVqG-9zF4D4bAGccRqsFD2rAK39bJ23QjANXCZ4k_a5lUw57cxoIJkdD5P8kSGUr7eADim94kvyDdQFFuGz_upWwdhMaiItvv2S_RIAdsf4SRVd81iM6CXBD32YLwGEGPpTF-v-ITV8SOkdBqJxxZCM0FzclBibdA82r4uD3lFKW8gv1XYLzW3y3s-_YlVg1m3eOxoDnY22k5UtUwhRnQu2RPmYVON4gYyT08wDcn27XCHs-DCTHUFWkJ_abGXOhceLFupTBqOi8NPBWbuQMu-OrnZ1hXqSm2WxA7YX_TUgJDI1wk0C4SkaAyUM1XruUVlORxjHwCWW_wW1xVIcFiaZO5ZTHC7cgOa_d1YbsnuxeGwCYbYjq0Pf1FNygktiosttYT09QTqE0upE2ds7qJt4BWVJg9ivqfF-0jiFbnastkX9jr3hAbMaiSHFRGeIJFUalN6jqZHyLOn1Sca4NkgxjBd3yKxpG-hBe4sYKcObam6ZwD7bLHu-UujXsgfJ5e8CXRbbgRC1OZ9by9m_QpNnOpLT6q1jFzwcCu1SU7RIR5qC0xe7AsiQFy8b


GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3


###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1009
Authorization: Bearer {{token}}


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

GET https://localhost:7005/api/restaurants/1009
Authorization: Bearer {{token}}


###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1009
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Updated name",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET https://localhost:7005/api/restaurants/3/dishes/7



###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###